### ISSUE TITLE
Week 2 lecture links broken

### ISSUE THREAD

**Issue by Johaning** [DS4PS/cpp-523-spr-2021#2]
The links from the class schedule page to the Week 2 lecture notes (all 5 links) and the summary of notation file linked just below them lead to Github 404 error pages. Can we get the correct links? 
Thanks!

**Comment by lecy** [comment]
GitHub just changed a naming convention for pages. We are working on updating links (some challenges because some links use the old convention still). But in general if you hit a broken link please let us know, but you can still find the file by changing "/master/" to "/main/": 

https://github.com/DS4PS/cpp-523-spr-2021/raw/master/lectures/p-01-variance-covariance-slope.pdf

https://github.com/DS4PS/cpp-523-spr-2021/raw/main/lectures/p-01-variance-covariance-slope.pdf
