### ISSUE TITLE
Lab-04 Solutions sheet--Do we want the slope of b1 to be positive?

### ISSUE THREAD

**Issue by mtwelker** [DS4PS/cpp-523-spr-2021#24]
In the explanation at the very end, it says that if our models show negative program effects and we know bias to be positive, "it would mean results can only get worse if the omitted variable is added, so it's not worth spending money on collecting new data...".

Does this mean that we should structure our models so that the slope of the policy variable will always be positive if the program is effective?  I'm thinking about an intervention to reduce dropout rates.  If our "Y" is the dropout rate, then a negative slope could mean the intervention is effective.  But based on the quote above, it sounds like the assumption is that an effective program has a positive slope, so it would be better to structure the model so that "Y" is a positive thing, like graduation rate instead.  Am I interpreting this right?

**Comment by lecy** [comment]
In this example more is better. The reasoning would be flipped if less is better. For example, classroom size and test scores.

**Comment by lecy** [comment]
If you know bias exists the slope is no longer your best guess of program effects. It is more like an upper or lower bound. You can eliminate a whole region of possibility knowing which direction the slope would shift if you could remove the bias. If the shift would not help your case for program impact then it’s good evidence that your program is not achieving the intended outcome. If the shift would be helpful then it should make you hesitant to interpret results because it could be bias suppressing program effects, not a real lack of impact. It’s mostly a reasoning exercise to help determine whether the biased model is worth interpreting, but it’s important to use the tools to reason through your current situation. There are no universal rules with these models. More a question about what you know about the data and the models, and how that shapes your own confidence in your own results.

**Comment by mtwelker** [comment]
That makes sense.  Apparently I was reading too much into the explanation.  Thanks!
