### ISSUE TITLE
How much R are we supposed to use to complete Lab-02?

### ISSUE THREAD

**Issue by mtwelker** [DS4PS/cpp-523-spr-2021#5]
Is the purpose of providing the R markdown file just to help us get comfortable with the format, or is the intent that we would figure out which statistical functions to use to make R figure out the answers?  I know how to enter my text answers in the .rmd document and use knitr to create an .html document with my answers, but I'm not sure if that's what the assignment is.

**Comment by mtwelker** [comment]
Never mind.  I've spent some more time on the r markdown file and I think I've figured it out.

**Comment by lecy** [comment]
It's a fair question. The program was designed so that students would start the first semester taking CPP 523 Intro to Program Eval and CPP 526 Intro to Data Science together. 

526 covers the basics of R and R Markdown, so we don't cover it in CPP 523.

Some students end up taking CPP 523 first and 526 later, in which case they might need a little help with the set-up. 

In general 523 is not grading you on your R skills, but you do need to be able to run regression functions and knit files for your labs. If you are stuck on anything R related in this class feel free to reach out for help. 

It's important get comfortable creating labs in RMD docs, though, because ultimately the goal is to be able to build models and be able to generate professional tables and graphs to communicate results. The R Markdown community has drawn on software from the publishing industry to create ways to combine your analytical steps with all of the formatting necessary to produce publication-quality reports. The passive knowledge you develop working with the RMD documents is actually a marketable skill. 

Every lab is an opportunity to practice both the analytical component as well as the communication component of answering data-driven questions. At the end of the program you should have a portfolio you can present to employers to show them what you can do. Invest in aesthetics and spend time learning tricks in RMD. It is a powerful platform. 

For CPP 523, though, you will not be tested on writing code. Most labs give you working code and you adapt it and answer the questions to show you understand the concepts. By the time you get to CPP 525 you will be asked to build your own datasets, do variable transformations, run models, and create tables without any sample code.

**Comment by mtwelker** [comment]
Thanks!  That's helpful.
