### ISSUE TITLE
Lab 4 uncertainty and a typo

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/cpp-523-spr-2021#8]
In Lab 4, starting with line 142, there is a prompt for Question #2. It states:

```
What happened to the slope of CSE?  
What happened to the standard error of CSE?  

How would our assessment of CSE change after we control for baseline self-esteem? For example, if we are a psychologist working with students should we worry if we observe a case where a person has a high need for approval from others? Will it impact their happiness? Or should we focus on other things? 
```

I don't understand what material this prompt is referring to. It almost seems like this is out of place?

Also, on line 150 there are 2 typos: should say `Question 2` and `caused`.

**Comment by jacobtnyoung** [comment]
This comes up again on line 152. Basically, it is not clear what is meant by `CSE` and `RSE`.

**Comment by jacobtnyoung** [comment]
Figured it out! I needed to read the instructions for the lab. Sorry! :)

**Comment by lecy** [comment]
Is it confusing because of variable definitions? 

* Rosemberg Self Esteem Scale (RSE) - one of many measures of self-esteem, a favorite variable in psychology. reference
* Contingent Self Esteem (CSE) - “is based on the approval of others or on social comparisons. The success or failure of any situation can result in fluctuations of an individual’s self-esteem. A manifestation of someone with contingent self-esteem is excessive self-consciousness…extreme criticism of one’s self, concern of how they are perceived by their peers, and feelings of discomfort in social settings.” 

The first question is mostly about the sign of CSE in model 1 vs model 3. Is having a high need for approval from others (CSE) problematic, from the therapist's standpoint. Will it have a positive or negative impact on the client's overall well-being? 

It's a tricky case, because it depends on the client's baseline self-esteem (RSE). Technically this model should include an interaction, but the class is not there yet. 

![image](https://user-images.githubusercontent.com/1209099/105897652-aec8cc80-5fd5-11eb-9dda-3ccef46f418a.png)

Thanks for the heads-up on typos!

**Comment by lecy** [comment]
Typos updated

**Comment by jacobtnyoung** [comment]
I was just going through the .Rmd file, not following the instructions. Thanks for the help!
